version: 2
updates:
    - package-ecosystem: npm
      directory: /
      schedule:
          interval: monthly
      open-pull-requests-limit: 5
      groups:
          linting:
              patterns:
                  - eslint
                  - "@eslint/*"
                  - typescript-eslint
          vscode-tooling:
              patterns:
                  - "@vscode/*"
      ignore:
          - dependency-name: typescript
            update-types:
                - version-update:semver-major
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: monthly
      open-pull-requests-limit: 5
      groups:
          github-actions:
              patterns:
                  - "*"
